[package]
name = "server_rs"
version = "1.0.0"
edition = "2021"

[lib]
name = "server_rs"
crate_type = ["cdylib"]

[dependencies]
log = "0"
jni = "0.21.0"
android_logger = "0.13.1"

server = { path = "../../TvShows/server" }

[profile.release]
codegen-units = 1
lto = true
strip = true
