/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pbs_server_http_ServerUtil */

#ifndef _Included_com_pbs_server_http_ServerUtil
#define _Included_com_pbs_server_http_ServerUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pbs_server_http_ServerUtil
 * Method:    startServer
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_pbs_server_http_ServerUtil_startServer
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
